import type { Metadata } from "next";
import { Geist_Mono, Karla } from "next/font/google";
import "./globals.css";
import LayoutRoot from "./RootLayout";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "@/context/SessionProvider";
import { getSession } from "@/lib/session";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const karla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${karla.variable} ${geistMono.variable} karla antialiased bg-[var(--color-background)]`}
      >
        <SessionProvider session={session as any}>
          <LayoutRoot>{children}</LayoutRoot>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
