import type { Metadata } from "next";
import { Geist_Mono, Karla } from "next/font/google";
import "./globals.css";
import LayoutRoot from "./RootLayout";
import { Toaster } from "@/components/ui/sonner";
import { getSession } from "@/lib/session";
import { AuthProvider } from "@/context/AuthContext";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const karla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${karla.variable} ${geistMono.variable} karla antialiased bg-(--color-background)`}
      >
        <AuthProvider>
          <LayoutRoot>{children}</LayoutRoot>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
