export * as AuthApis from './auth/auth.api'
export * as CollectionApis from './collection/collection.api'
export * as UploadApis from './upload/upload.api'
export * as ProductApis from './product/product.api'
export * as CartApis from './cart/cart.api'